export const ADD_CLIENTS = "ADD_CLIENTS";
export const EDITING_CLIENTS = "EDITING_CLIENTS";
export const UPDATE_EDITING_CLIENTS = "UPDATE_EDITING_CLIENTS";
export const SAVE_EDITING_CLIENTS = "SAVE_EDITING_CLIENTS";
export const LOADING_CLIENTS = "LOADING_CLIENTS";
